# Generated by Django 4.0 on 2024-07-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="compartments",
            field=models.ManyToManyField(to="packr.Compartment"),
        ),
    ]
