# Generated by Django 4.0 on 2024-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packr", "0002_item_compartments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bag",
            name="dimension_x",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bag",
            name="dimension_y",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bag",
            name="dimension_z",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="compartment",
            name="dimension_x",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="compartment",
            name="dimension_y",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="compartment",
            name="dimension_z",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="dimension_x",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="dimension_y",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="dimension_z",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="weight",
            field=models.FloatField(),
        ),
    ]
