# Generated by Django 4.0 on 2024-07-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("packr", "0005_pack_remove_trip_traveler_rename_item_name_item_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="traveler",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.user",
            ),
        ),
    ]
