# Generated by Django 4.0 on 2024-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packr", "0006_pack_traveler"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
