# Generated by Django 4.2.3 on 2024-08-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packr', '0008_alter_pack_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reference_pk',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
